version: '3'

env:
  VERSION: "1.0.0"
  MESSAGE: "boardwall > added initial files"

tasks:
  commit:
    desc: Committing changes
    cmds:
      - git add .
      - git commit -m "$MESSAGE"
      - git push -f
      - git tag -a "v{{.VERSION}}" -m "Version {{.VERSION}}"

  run-frontend:
    desc: Run the frontend application
    dir: frontend
    cmds:
      - npm start

  run-backend:
    desc: Run the backend application
    dir: backend
    cmds:
      - go run main.go

  build-frontend:
    desc: Build the application
    dir: frontend
    cmds:
      - ng build --configuration development

  build-backend:
    desc: Build the backend
    dir: backend
    cmds:
      - go build -o bin/boardwall-backend main.go

  build-and-run-container:
    desc: Build boardwall-aio
    cmds:
      - docker stop boardwall-aio
      - docker build -t boardwall-aio:latest -f Dockerfile .
      # - docker network create datanet
      - docker compose -f docker-compose.yml up -d
      - docker logs -f boardwall-aio