version: '3'

env:
  VERSION: "v1.1.2"
  MESSAGE: "boardwall > added working files"

tasks:
  commit:
    desc: Committing changes
    cmds:
      - git add .
      - git commit -m "{{.VERSION}} $MESSAGE"
      - git push -f
      - git tag -a "{{.VERSION}}" -m "Version {{.VERSION}}"

  run:frontend:
    desc: Run the frontend application
    dir: frontend
    cmds:
      - npm start

  run:backend:
    desc: Run the backend application
    dir: backend
    dotenv: ['../.env.dev']
    cmds:
      - sh run.sh

  build:frontend:
    desc: Build the application
    dir: frontend
    cmds:
      - ng build --configuration development

  build:backend:
    desc: Build the backend
    dir: backend
    cmds:
      - mvn clean install
      - mvn dependency:go-offline
      - mvn clean package -DskipTests

  build-and-run:
    desc: Build boardwall-aio
    dotenv: ['.env']
    cmds:
      - docker stop boardwall-aio
      # - docker rmi $(docker images -f "dangling=true")
      - docker build -t boardwall-aio:latest -f Dockerfile .
      # - docker network create datanet
      - docker compose -f docker-compose.yml up -d
      - docker logs -f boardwall-aio
  
  stop:
    desc: Stop the application
    cmds:
      - docker stop boardwall-aio